### ISSUE TITLE
ImportError: No module named sbf

### ISSUE THREAD

**Issue by mivade** [jashandeep-sohi/pysbf#2]
After running `python setup.py install` and trying to import `pysbf`, I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pysbf/__init__.py", line 1, in <module>
    from sbf import load
ImportError: No module named sbf
```

The build was successful, and (using a virtualenv) when I look in `env/lib/python<version>/site-packages/pysbf` there is indeed a sbf.so that exists. This is on Linux (amd64) and I have tried with Python 2.7 and 3.4.

**Comment by jashandeep-sohi** [comment]
Have you tried installing from pip? I just did the following and everything seems to be working:
```
$ virtualenv2 test
New python executable in .../test/bin/python2
Also creating executable in .../test/bin/python
Installing setuptools, pip, wheel...done.
$ source test/bin/activate
(test)$ pip install --no-cache-dir pysbf
Collecting pysbf
  Downloading pysbf-0.6.1.tar.bz2 (175kB)
    100% |████████████████████████████████| 184kB 850kB/s 
Installing collected packages: pysbf
  Running setup.py install for pysbf ... done
Successfully installed pysbf-0.6.1
(test)$ python2
Python 2.7.11 (default, Mar 31 2016, 06:18:34) 
[GCC 5.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysbf
>>> pysbf.__file__
'.../test/lib/python2.7/site-packages/pysbf/__init__.pyc'
>>> pysbf.sbf
<module 'pysbf.sbf' from '.../test/lib/python2.7/site-packages/pysbf/sbf.so'>
>>> pysbf.load
<built-in function load>
```

What's the exact version of python 2 that you're using?

And BTW, I don't think the module will work with python 3.x (you could try, but I'm not sure what the expected behaviour is).

**Comment by mivade** [comment]
Strange, it works fine with pip if I use the system Python 2.7 (2.7.9). I am using Anaconda, so maybe something funny is going on there.

**Comment by Nodd** [comment]
I had the same problem, and the answer is simply that the python module name is not `sbf` but `pysbf`.
